import React, { useState, useMemo } from 'react';
import { 
  Building2, 
  TrendingUp, 
  DollarSign, 
  MapPin, 
  ShieldCheck, 
  Sliders, 
  Award, 
  CheckCircle2, 
  AlertTriangle, 
  ArrowRight, 
  Sparkles, 
  Download, 
  BarChart3, 
  Compass, 
  Fuel, 
  Store, 
  Zap, 
  Layers, 
  Flame, 
  Check, 
  Plus
} from 'lucide-react';
import { WhiteSpotCandidate, StoreLocationRecord } from '../types';

interface InvestmentMatrixProps {
  candidates: WhiteSpotCandidate[];
  locations: StoreLocationRecord[];
  onSelectCandidateForMap?: (candidate: WhiteSpotCandidate) => void;
  onOpenAIRecommendation?: (candidate: WhiteSpotCandidate) => void;
}

export const InvestmentMatrixModule: React.FC<InvestmentMatrixProps> = ({
  candidates,
  locations,
  onSelectCandidateForMap,
  onOpenAIRecommendation
}) => {
  // Select up to 4 shortlisted sites for head-to-head comparison
  const [selectedSiteIds, setSelectedSiteIds] = useState<string[]>(() => {
    if (candidates.length >= 3) {
      return candidates.slice(0, 3).map(c => c.id);
    }
    return candidates.slice(0, 2).map(c => c.id);
  });

  // Custom criteria weights (sum to 100)
  const [weights, setWeights] = useState({
    trafficAadt: 25,
    unmetDemandGap: 25,
    irrAndPayback: 20,
    competitorMoat: 15,
    cannibalizationShield: 15
  });

  const [activeViewTab, setActiveViewTab] = useState<'matrix' | 'tradeoffs' | 'radar'>('matrix');

  // Shortlisted candidates
  const shortlisted = useMemo(() => {
    return candidates.filter(c => selectedSiteIds.includes(c.id));
  }, [candidates, selectedSiteIds]);

  // Compute weighted investment score for each site
  const rankedSites = useMemo(() => {
    const totalW = weights.trafficAadt + weights.unmetDemandGap + weights.irrAndPayback + weights.competitorMoat + weights.cannibalizationShield || 100;

    return shortlisted.map(site => {
      const trafficNorm = Math.min(100, Math.round(((site.aadt || 35000) / 60000) * 100));
      const demandNorm = Math.min(100, site.demandScore || 80);
      const irrNorm = Math.min(100, Math.round(((site.estimatedIrrPct || 22) / 32) * 100));
      const compNorm = Math.min(100, site.supplyGapScore || 75);
      const cannNorm = site.riskLevel === 'Low' ? 95 : site.riskLevel === 'Moderate' ? 70 : 45;

      const weightedScore = Math.round(
        (trafficNorm * weights.trafficAadt +
         demandNorm * weights.unmetDemandGap +
         irrNorm * weights.irrAndPayback +
         compNorm * weights.competitorMoat +
         cannNorm * weights.cannibalizationShield) / totalW
      );

      return {
        ...site,
        trafficNorm,
        demandNorm,
        irrNorm,
        compNorm,
        cannNorm,
        weightedScore
      };
    }).sort((a, b) => b.weightedScore - a.weightedScore);
  }, [shortlisted, weights]);

  const topPick = rankedSites[0];

  const toggleSiteSelection = (id: string) => {
    if (selectedSiteIds.includes(id)) {
      if (selectedSiteIds.length > 2) {
        setSelectedSiteIds(prev => prev.filter(i => i !== id));
      }
    } else {
      if (selectedSiteIds.length < 4) {
        setSelectedSiteIds(prev => [...prev, id]);
      } else {
        // replace last
        setSelectedSiteIds(prev => [...prev.slice(0, 3), id]);
      }
    }
  };

  const handleExportMemo = () => {
    const lines = [
      'INVESTMENT COMMITTEE MULTI-SITE HEAD-TO-HEAD MATRIX',
      `Date: ${new Date().toLocaleDateString()}`,
      `Generated by WhiteSpot Location Intelligence Platform\n`,
      'RANKING SUMMARY:',
      ...rankedSites.map((s, idx) => 
        `#${idx + 1} - ${s.candidateName} [Score: ${s.weightedScore}/100] | CapEx: $${(s.estimatedCapEx / 1000000).toFixed(2)}M | IRR: ${s.estimatedIrrPct}% | Payback: ${s.estimatedPaybackYears} yrs | AADT: ${(s.aadt || 0).toLocaleString()} | Fuel Vol: ${(s.projectedAnnualFuelGallons / 1000000).toFixed(2)}M gal`
      ),
      '\nRECOMMENDED CAPITAL ALLOCATION:',
      `Top Pick: ${topPick?.candidateName} represents the highest risk-adjusted yield with an estimated IRR of ${topPick?.estimatedIrrPct}% and ${(topPick?.aadt || 0).toLocaleString()} daily vehicular throughput.`
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `investment_matrix_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 pb-12 font-sans text-purple-950">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-purple-900 via-indigo-900 to-purple-950 rounded-3xl p-6 text-white shadow-xl border border-purple-800/40 relative overflow-hidden">
        <div className="absolute right-0 top-0 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 relative z-10">
          <div>
            <div className="flex items-center space-x-2 text-purple-300 text-xs font-bold uppercase tracking-wider mb-1">
              <Award className="w-4 h-4 text-amber-400" />
              <span>Investment Committee Decision Engine</span>
            </div>
            <h1 className="text-2xl font-black tracking-tight">Multi-Site Head-to-Head Benchmark Matrix</h1>
            <p className="text-sm text-purple-200 mt-1 max-w-2xl">
              Side-by-side trade-off evaluation for shortlisted candidate forecourts with customizable underwriting weightings.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleExportMemo}
              className="px-4 py-2.5 rounded-xl bg-purple-700/60 hover:bg-purple-600 text-xs font-bold text-white border border-purple-500/30 shadow-md flex items-center gap-2 cursor-pointer transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Export IC Memo</span>
            </button>
          </div>
        </div>
      </div>

      {/* Candidate Selector Chips */}
      <div className="bg-white rounded-2xl p-4 border border-purple-100 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-3">
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-900">
              Shortlisted Candidates ({selectedSiteIds.length}/4 selected)
            </h3>
            <p className="text-[11px] text-purple-600">Select 2 to 4 parcels to run head-to-head trade-off scoring</p>
          </div>

          <div className="flex items-center gap-1.5 text-xs">
            <button
              onClick={() => setActiveViewTab('matrix')}
              className={`px-3 py-1.5 rounded-xl font-bold transition-all cursor-pointer ${
                activeViewTab === 'matrix'
                  ? 'bg-purple-600 text-white shadow-sm'
                  : 'bg-purple-50 text-purple-800 hover:bg-purple-100'
              }`}
            >
              Matrix Table
            </button>
            <button
              onClick={() => setActiveViewTab('tradeoffs')}
              className={`px-3 py-1.5 rounded-xl font-bold transition-all cursor-pointer ${
                activeViewTab === 'tradeoffs'
                  ? 'bg-purple-600 text-white shadow-sm'
                  : 'bg-purple-50 text-purple-800 hover:bg-purple-100'
              }`}
            >
              Trade-Offs & SWOT
            </button>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {candidates.map(c => {
            const isSelected = selectedSiteIds.includes(c.id);
            return (
              <button
                key={c.id}
                onClick={() => toggleSiteSelection(c.id)}
                className={`px-3 py-2 rounded-xl text-xs font-medium border transition-all flex items-center gap-2 cursor-pointer ${
                  isSelected
                    ? 'bg-purple-100 border-purple-500 text-purple-950 font-bold shadow-sm'
                    : 'bg-white border-purple-200 text-slate-600 hover:border-purple-300 hover:bg-purple-50/50'
                }`}
              >
                <div className={`w-4 h-4 rounded-md flex items-center justify-center text-[10px] ${
                  isSelected ? 'bg-purple-600 text-white' : 'border border-purple-300'
                }`}>
                  {isSelected && <Check className="w-3 h-3" />}
                </div>
                <span>{c.candidateName}</span>
                <span className="text-[10px] text-purple-500 font-mono">({c.city})</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Top Pick Highlight Card */}
      {topPick && (
        <div className="bg-gradient-to-r from-purple-50 via-indigo-50/60 to-purple-50 rounded-2xl p-5 border border-purple-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-400 to-amber-600 text-white flex items-center justify-center font-black text-xl shadow-md flex-shrink-0">
              #1
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-amber-700 bg-amber-100 px-2 py-0.5 rounded-md uppercase tracking-wider">
                  Top Recommended Pick
                </span>
                <span className="text-xs font-bold text-purple-700">Composite Score: {topPick.weightedScore}/100</span>
              </div>
              <h2 className="text-lg font-black text-purple-950 mt-1">{topPick.candidateName}</h2>
              <p className="text-xs text-purple-700 flex items-center gap-1.5 mt-0.5">
                <MapPin className="w-3.5 h-3.5 text-purple-500" />
                <span>{topPick.address}</span>
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-4 border-t md:border-t-0 md:border-l border-purple-200 pt-3 md:pt-0 md:pl-5 text-xs">
            <div>
              <div className="text-[10px] uppercase font-bold text-purple-500">Unlevered IRR</div>
              <div className="text-base font-black text-emerald-600">{topPick.estimatedIrrPct}%</div>
            </div>
            <div>
              <div className="text-[10px] uppercase font-bold text-purple-500">Est. Payback</div>
              <div className="text-base font-black text-purple-900">{topPick.estimatedPaybackYears} yrs</div>
            </div>
            <div>
              <div className="text-[10px] uppercase font-bold text-purple-500">CapEx</div>
              <div className="text-base font-black text-purple-900">${(topPick.estimatedCapEx / 1000000).toFixed(2)}M</div>
            </div>
            <div>
              <div className="text-[10px] uppercase font-bold text-purple-500">Annual EBITDA</div>
              <div className="text-base font-black text-emerald-700">${((topPick.projectedAnnualEbitda || 850000) / 1000).toFixed(0)}k</div>
            </div>

            {onSelectCandidateForMap && (
              <button
                onClick={() => onSelectCandidateForMap(topPick)}
                className="px-3.5 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white font-bold transition-all shadow-sm flex items-center gap-1.5 cursor-pointer ml-auto"
              >
                <span>View on Map</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      )}

      {/* Underwriting Weights Slider Customizer */}
      <div className="bg-white rounded-2xl p-5 border border-purple-100 shadow-sm space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Sliders className="w-4 h-4 text-purple-600" />
            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-900">
              Customize Committee Scoring Weightings
            </h3>
          </div>
          <span className="text-xs text-purple-600 font-medium">Real-time rank recalculation</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
          <div>
            <div className="flex justify-between text-xs font-bold mb-1">
              <span className="text-purple-900">Traffic AADT</span>
              <span className="text-purple-600">{weights.trafficAadt}%</span>
            </div>
            <input
              type="range"
              min="5"
              max="50"
              value={weights.trafficAadt}
              onChange={(e) => setWeights(prev => ({ ...prev, trafficAadt: parseInt(e.target.value) }))}
              className="w-full accent-purple-600 cursor-pointer"
            />
          </div>

          <div>
            <div className="flex justify-between text-xs font-bold mb-1">
              <span className="text-purple-900">Demand & Gap Void</span>
              <span className="text-purple-600">{weights.unmetDemandGap}%</span>
            </div>
            <input
              type="range"
              min="5"
              max="50"
              value={weights.unmetDemandGap}
              onChange={(e) => setWeights(prev => ({ ...prev, unmetDemandGap: parseInt(e.target.value) }))}
              className="w-full accent-purple-600 cursor-pointer"
            />
          </div>

          <div>
            <div className="flex justify-between text-xs font-bold mb-1">
              <span className="text-purple-900">IRR & Payback</span>
              <span className="text-purple-600">{weights.irrAndPayback}%</span>
            </div>
            <input
              type="range"
              min="5"
              max="50"
              value={weights.irrAndPayback}
              onChange={(e) => setWeights(prev => ({ ...prev, irrAndPayback: parseInt(e.target.value) }))}
              className="w-full accent-purple-600 cursor-pointer"
            />
          </div>

          <div>
            <div className="flex justify-between text-xs font-bold mb-1">
              <span className="text-purple-900">Competitor Moat</span>
              <span className="text-purple-600">{weights.competitorMoat}%</span>
            </div>
            <input
              type="range"
              min="5"
              max="50"
              value={weights.competitorMoat}
              onChange={(e) => setWeights(prev => ({ ...prev, competitorMoat: parseInt(e.target.value) }))}
              className="w-full accent-purple-600 cursor-pointer"
            />
          </div>

          <div>
            <div className="flex justify-between text-xs font-bold mb-1">
              <span className="text-purple-900">Cannibalization Shield</span>
              <span className="text-purple-600">{weights.cannibalizationShield}%</span>
            </div>
            <input
              type="range"
              min="5"
              max="50"
              value={weights.cannibalizationShield}
              onChange={(e) => setWeights(prev => ({ ...prev, cannibalizationShield: parseInt(e.target.value) }))}
              className="w-full accent-purple-600 cursor-pointer"
            />
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      {activeViewTab === 'matrix' ? (
        <div className="bg-white rounded-2xl border border-purple-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-purple-50/80 border-b border-purple-100 text-[11px] font-bold text-purple-900 uppercase tracking-wider">
                  <th className="p-4 w-1/4">Evaluation Metric</th>
                  {rankedSites.map((site, idx) => (
                    <th key={site.id} className="p-4 text-center">
                      <div className="flex items-center justify-center gap-1.5">
                        <span className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] text-white font-bold ${
                          idx === 0 ? 'bg-amber-500' : 'bg-purple-600'
                        }`}>
                          #{idx + 1}
                        </span>
                        <span className="font-extrabold text-purple-950 truncate max-w-[160px]">{site.candidateName}</span>
                      </div>
                      <div className="text-[10px] font-normal text-purple-600 font-mono mt-0.5">{site.city}, {site.state}</div>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-purple-50 font-medium">
                {/* 1. Weighted Composite Score */}
                <tr className="bg-purple-50/30">
                  <td className="p-4 font-bold text-purple-950 flex items-center gap-2">
                    <Award className="w-4 h-4 text-amber-500" />
                    <span>Composite Rank Score</span>
                  </td>
                  {rankedSites.map((site, idx) => (
                    <td key={site.id} className="p-4 text-center">
                      <span className={`text-base font-black px-2.5 py-1 rounded-xl ${
                        idx === 0 ? 'bg-amber-100 text-amber-900 border border-amber-300' : 'bg-purple-100 text-purple-900'
                      }`}>
                        {site.weightedScore}/100
                      </span>
                    </td>
                  ))}
                </tr>

                {/* 2. CapEx & Financials */}
                <tr>
                  <td className="p-4 font-bold text-purple-900">Estimated CapEx</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      ${(site.estimatedCapEx / 1000000).toFixed(2)}M
                    </td>
                  ))}
                </tr>

                <tr>
                  <td className="p-4 font-bold text-purple-900">Unlevered IRR</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-black text-emerald-600 text-sm">
                      {site.estimatedIrrPct}%
                    </td>
                  ))}
                </tr>

                <tr>
                  <td className="p-4 font-bold text-purple-900">Capital Payback Period</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {site.estimatedPaybackYears} Years
                    </td>
                  ))}
                </tr>

                <tr>
                  <td className="p-4 font-bold text-purple-900">Projected Annual EBITDA</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-emerald-700">
                      ${((site.projectedAnnualEbitda || 850000) / 1000).toFixed(0)}k
                    </td>
                  ))}
                </tr>

                {/* 3. Operational Configuration */}
                <tr className="bg-purple-50/20">
                  <td className="p-4 font-bold text-purple-900">Recommended Forecourt MPD / Pumps</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {site.recommendedPumps} Positions ({site.forecourtPumps?.dieselHdvLanes ? `${site.forecourtPumps.dieselHdvLanes} Diesel Lanes` : 'Auto Gas'})
                    </td>
                  ))}
                </tr>

                <tr className="bg-purple-50/20">
                  <td className="p-4 font-bold text-purple-900">C-Store Footprint Size</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {(site.recommendedCStoreSqFt || 0).toLocaleString()} Sq Ft
                    </td>
                  ))}
                </tr>

                {/* 4. Traffic & Demographics */}
                <tr>
                  <td className="p-4 font-bold text-purple-900">Corridor AADT Traffic</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {(site.aadt || 0).toLocaleString()} Daily Vehicles
                    </td>
                  ))}
                </tr>

                <tr>
                  <td className="p-4 font-bold text-purple-900">3-Mile Catchment Population</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {(site.pop3Mile || 0).toLocaleString()} Residents
                    </td>
                  ))}
                </tr>

                <tr>
                  <td className="p-4 font-bold text-purple-900">Unmet Fuel Demand Deficit</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {(site.projectedAnnualFuelGallons / 1000000).toFixed(2)}M Gallons/Year
                    </td>
                  ))}
                </tr>

                {/* 5. Competitors & Moat */}
                <tr className="bg-purple-50/30">
                  <td className="p-4 font-bold text-purple-900">Nearest Competing Station</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center font-bold text-purple-950">
                      {site.nearestStationMiles} Miles Away
                    </td>
                  ))}
                </tr>

                <tr className="bg-purple-50/30">
                  <td className="p-4 font-bold text-purple-900">Cannibalization Risk Level</td>
                  {rankedSites.map(site => (
                    <td key={site.id} className="p-4 text-center">
                      <span className={`px-2.5 py-1 rounded-full text-[11px] font-bold ${
                        site.riskLevel === 'Low'
                          ? 'bg-emerald-100 text-emerald-800'
                          : site.riskLevel === 'Moderate'
                          ? 'bg-amber-100 text-amber-800'
                          : 'bg-rose-100 text-rose-800'
                      }`}>
                        {site.riskLevel} Risk
                      </span>
                    </td>
                  ))}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* Trade-offs and SWOT view */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {rankedSites.map((site, idx) => (
            <div key={site.id} className="bg-white rounded-2xl p-5 border border-purple-100 shadow-sm space-y-4 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className={`px-2.5 py-1 rounded-xl text-xs font-bold ${
                    idx === 0 ? 'bg-amber-100 text-amber-800 border border-amber-300' : 'bg-purple-100 text-purple-900'
                  }`}>
                    Rank #{idx + 1} • {site.weightedScore} pts
                  </span>
                  <span className="text-xs font-black text-emerald-600">{site.estimatedIrrPct}% IRR</span>
                </div>

                <h3 className="text-sm font-black text-purple-950">{site.candidateName}</h3>
                <p className="text-xs text-purple-600 mt-0.5">{site.address}</p>

                <div className="mt-4 space-y-2">
                  <div className="text-[11px] font-bold text-emerald-700 uppercase tracking-wider">Key Strengths</div>
                  <ul className="space-y-1 text-xs text-slate-600">
                    <li className="flex items-start gap-1.5">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0 mt-0.5" />
                      <span>{(site.projectedAnnualFuelGallons / 1000000).toFixed(2)}M gal/yr unmet fuel demand void</span>
                    </li>
                    <li className="flex items-start gap-1.5">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0 mt-0.5" />
                      <span>{(site.aadt || 0).toLocaleString()} daily vehicle AADT corridor throughput</span>
                    </li>
                  </ul>
                </div>

                <div className="mt-3 space-y-2">
                  <div className="text-[11px] font-bold text-amber-700 uppercase tracking-wider">Underwriting Watch Items</div>
                  <ul className="space-y-1 text-xs text-slate-600">
                    <li className="flex items-start gap-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-amber-500 flex-shrink-0 mt-0.5" />
                      <span>{site.competitorCount3Miles} competing stations within 3-mile ring</span>
                    </li>
                    <li className="flex items-start gap-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-amber-500 flex-shrink-0 mt-0.5" />
                      <span>CapEx requirement of ${(site.estimatedCapEx / 1000000).toFixed(2)}M</span>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="pt-3 border-t border-purple-100 flex items-center justify-between">
                {onSelectCandidateForMap && (
                  <button
                    onClick={() => onSelectCandidateForMap(site)}
                    className="text-xs font-bold text-purple-600 hover:text-purple-900 cursor-pointer flex items-center gap-1"
                  >
                    <span>View Map</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                )}

                {onOpenAIRecommendation && (
                  <button
                    onClick={() => onOpenAIRecommendation(site)}
                    className="px-3 py-1.5 rounded-xl bg-purple-100 hover:bg-purple-200 text-purple-900 font-bold text-xs transition-all cursor-pointer flex items-center gap-1.5"
                  >
                    <Sparkles className="w-3.5 h-3.5 text-purple-600" />
                    <span>AI Underwrite</span>
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
