import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  Sparkles, 
  CheckCircle2, 
  Layers, 
  DollarSign, 
  MapPin, 
  Fuel, 
  Store, 
  ShieldCheck, 
  Share2 
} from 'lucide-react';
import { WhiteSpotCandidate, StoreLocationRecord } from '../types';

interface ReportsExportsProps {
  candidates: WhiteSpotCandidate[];
  locations: StoreLocationRecord[];
}

export const ReportsExports: React.FC<ReportsExportsProps> = ({ candidates, locations }) => {
  const [selectedCandidateId, setSelectedCandidateId] = useState<string>(candidates[0]?.id || '');
  const activeCandidate = candidates.find(c => c.id === selectedCandidateId) || candidates[0] || null;

  if (!activeCandidate) {
    return (
      <div className="p-6 max-w-5xl mx-auto space-y-6">
        <div className="p-8 bg-white border border-purple-200 rounded-3xl text-center space-y-4 shadow-xl">
          <div className="w-16 h-16 bg-purple-100 border border-purple-200 text-purple-700 rounded-2xl flex items-center justify-center mx-auto shadow-inner">
            <FileText className="w-8 h-8" />
          </div>
          <h2 className="text-xl font-black text-purple-950">No Investment Memorandums Available</h2>
          <p className="text-xs text-purple-700 max-w-md mx-auto">
            Scan for trade area voids or click anywhere on the live map to generate comprehensive underwriting memos and exportable dossiers.
          </p>
        </div>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const memoText = `# EXECUTIVE INVESTMENT MEMORANDUM
## WhiteSpot Intelligence Platform - Site Evaluation

**Target Location:** ${activeCandidate.candidateName}
**Address:** ${activeCandidate.address || ''}, ${activeCandidate.city || ''}, ${activeCandidate.state || ''} ${activeCandidate.zipCode || ''}
**Opportunity Score:** ${activeCandidate.opportunityScore} / 100
**Risk Profile:** ${activeCandidate.riskLevel} Risk

---

### 1. Executive Summary & Recommendation
The site at ${activeCandidate.candidateName} presents a tier-1 retail fuel and convenience expansion opportunity. With daily traffic of ${(activeCandidate.aadt || 0).toLocaleString()} AADT along the primary corridor and a 3-mile population of ${(activeCandidate.pop3Mile || 0).toLocaleString()} (Median Income: $${(activeCandidate.medianIncome3Mile || 0).toLocaleString()}), the location demonstrates high unmet commercial demand.

### 2. Underwriting & Financial Feasibility
- **Turnkey Estimated CapEx:** $${((activeCandidate.estimatedCapEx || 0) / 1000000).toFixed(2)}M
- **Projected Annual Fuel Volume:** ${((activeCandidate.projectedAnnualFuelGallons || 0) / 1000000).toFixed(2)}M Gallons
- **Projected Annual Total Gross Revenue:** ${((activeCandidate.projectedAnnualTotalRevenue || 0) / 1000000).toFixed(2)}M
- **Projected Annual EBITDA:** ${((activeCandidate.projectedAnnualEbitda || 0) / 1000000).toFixed(2)}M
- **Unlevered IRR:** ${activeCandidate.estimatedIrrPct}%
- **Payback Period:** ${activeCandidate.estimatedPaybackYears} Years

### 3. Proposed Physical Store Format
- **Format Type:** ${activeCandidate.proposedStoreType}
- **Recommended Dispenser Pumps:** ${activeCandidate.recommendedPumps} Multi-Product Dispensers (${activeCandidate.recommendedPumps * 2} fueling positions)
- **C-Store Retail Footprint:** ${(activeCandidate.recommendedCStoreSqFt || 0).toLocaleString()} sq ft
- **EV DC Fast Charging:** 8x 350kW High-Power Ports (NEVI Compliant)

### 4. Key Decision Rationales
${(activeCandidate.primaryRationale || []).map(r => `- ${r}`).join('\n')}

---
*Report generated by WhiteSpot Intelligence Geospatial Platform*
`;

    const blob = new Blob([memoText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Investment_Memo_${activeCandidate.id}.md`;
    a.click();
  };

  return (
    <div className="p-4 lg:p-8 space-y-6 max-w-5xl mx-auto font-sans">
      {/* Header & Export Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white border border-purple-200 p-5 rounded-3xl shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full bg-purple-100 text-purple-800 border border-purple-200 text-xs font-bold flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5 text-purple-700" />
              Executive Dossier
            </span>
            <span className="text-xs text-purple-600 font-mono">Investment Committee Format</span>
          </div>
          <h2 className="text-2xl font-black text-purple-950 tracking-tight">
            Executive Investment Memorandum
          </h2>
        </div>

        <div className="flex items-center gap-2.5">
          <select
            value={activeCandidate.id}
            onChange={(e) => setSelectedCandidateId(e.target.value)}
            className="bg-purple-50 text-xs text-purple-950 px-3 py-2 rounded-xl border border-purple-200 focus:outline-none focus:border-purple-600 font-bold cursor-pointer"
          >
            {candidates.map(c => (
              <option key={c.id} value={c.id}>
                {c.candidateName} ({c.city}, {c.state})
              </option>
            ))}
          </select>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3.5 py-2 rounded-xl bg-purple-100 hover:bg-purple-200 text-purple-950 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer border border-purple-200"
          >
            <Download className="w-3.5 h-3.5 text-purple-700" />
            <span>Download .MD</span>
          </button>

          <button
            onClick={handlePrint}
            className="px-3.5 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer shadow-md shadow-purple-500/20"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Investment Memo Paper Style Container */}
      <div className="bg-white border border-purple-200 rounded-3xl p-6 sm:p-10 space-y-6 text-purple-950 shadow-2xl">
        {/* Memo Header */}
        <div className="border-b border-purple-100 pb-6 space-y-3">
          <div className="flex justify-between items-start">
            <div>
              <div className="text-[10px] uppercase font-mono tracking-widest text-purple-600 font-bold">
                WHITESPOT INTELLIGENCE • LOCATION UNDERWRITING
              </div>
              <h1 className="text-2xl sm:text-3xl font-black text-purple-950 mt-1">
                {activeCandidate.candidateName}
              </h1>
              <p className="text-xs text-purple-700">
                {activeCandidate.address}, {activeCandidate.city}, {activeCandidate.state} {activeCandidate.zipCode || ''}
              </p>
            </div>

            <div className="text-right">
              <div className="text-[10px] text-purple-600 uppercase font-bold">Opportunity Score</div>
              <div className="text-3xl font-black text-purple-700">{activeCandidate.opportunityScore}<span className="text-sm font-normal text-purple-500">/100</span></div>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-purple-100 text-purple-900 border border-purple-200">
                {activeCandidate.riskLevel} Risk Profile
              </span>
            </div>
          </div>
        </div>

        {/* Core Financial & Capacity Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-2xl bg-purple-50/50 border border-purple-100">
            <div className="text-[11px] text-purple-600 font-semibold">Total Turnkey CapEx</div>
            <div className="text-xl font-black text-purple-950 mt-1">${((activeCandidate.estimatedCapEx || 0) / 1000000).toFixed(2)}M</div>
          </div>
          <div className="p-4 rounded-2xl bg-purple-50/50 border border-purple-100">
            <div className="text-[11px] text-purple-600 font-semibold">Projected Annual Fuel</div>
            <div className="text-xl font-black text-purple-950 mt-1">{((activeCandidate.projectedAnnualFuelGallons || 0) / 1000000).toFixed(2)}M gal</div>
          </div>
          <div className="p-4 rounded-2xl bg-purple-50/50 border border-purple-100">
            <div className="text-[11px] text-purple-600 font-semibold">Projected EBITDA</div>
            <div className="text-xl font-black text-emerald-600 mt-1">${((activeCandidate.projectedAnnualEbitda || 0) / 1000000).toFixed(2)}M</div>
          </div>
          <div className="p-4 rounded-2xl bg-purple-50/50 border border-purple-100">
            <div className="text-[11px] text-purple-600 font-semibold">Estimated Payback</div>
            <div className="text-xl font-black text-purple-700 mt-1">{activeCandidate.estimatedPaybackYears} Yrs</div>
          </div>
        </div>

        {/* Key Rationales */}
        <div className="space-y-3 pt-2">
          <h3 className="text-sm font-bold text-purple-950 uppercase tracking-wider">
            Key Underwriting Rationales
          </h3>
          <div className="space-y-2">
            {(activeCandidate.primaryRationale || []).map((rat, idx) => (
              <div key={idx} className="flex items-start gap-2.5 p-3 rounded-xl bg-purple-50/30 border border-purple-100 text-xs text-purple-900">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                <span>{rat}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
